name: international_system_of_units_locale
description: All the units in your locale
version: 1.0.0-dev.4
repository: https://github.com/Kleak/international_system_of_units
homepage: https://github.com/Kleak/international_system_of_units/blob/master/packages/international_system_of_units_locale/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  test: ^1.20.1
  intl_generator: ^0.2.1
  lints: ^1.0.1
