name: international_system_of_units_locale
description: All the units in your locale
version: 1.0.0-dev.3
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  intl_translation: ^0.17.10
