name: international_system_of_units_locale
description: All the units in your locale
version: 1.0.0-dev.4
repository: https://github.com/Kleak/international_system_of_units
homepage: https://github.com/Kleak/international_system_of_units/blob/master/packages/international_system_of_units_locale/README.md

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  intl_generator: ^0.2.1
