name: international_system_of_units
description: The most complete unit converter for Dart/Flutter which also do localizations.
version: 1.0.0-dev.5
repository: https://github.com/Kleak/international_system_of_units
homepage: https://github.com/Kleak/international_system_of_units/blob/master/packages/international_system_of_units_locale/README.md

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  international_system_of_units_locale: ^1.0.0-dev.4

dev_dependencies:
  pedantic: ^1.8.0
  intl_generator: ^0.2.1
  test: ^1.14.3
