name: international_system_of_units
description: The most complete unit converter for Dart/Flutter which also do localizations.
version: 1.0.0-dev.5
repository: https://github.com/Kleak/international_system_of_units
homepage: https://github.com/Kleak/international_system_of_units/blob/master/packages/international_system_of_units_locale/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.18.0
  international_system_of_units_locale:
    git:
      url: https://github.com/Letalus/international_system_of_units.git
      ref: null_safety
      path: packages/international_system_of_units_locale/
      publish_to: None

dev_dependencies:
  intl_generator: ^0.2.1
  lints: ^1.0.1
  test: ^1.14.3
