name: Ci on pull request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Check format
        run: dartfmt -n --set-exit-if-changed .
      - name: Dart analyze
        run: dartanalyzer --options=analysis_options.yaml --fatal-hints --fatal-warnings .
      - name: Run tests
        run: pub run test
